### ISSUE TITLE
CMakeLists.txt OpenCV path

### ISSUE THREAD

**Issue by bhomaidan1990** [ravijo/realsense-calibration#1]
In order to make CMake work perfectly I changed the OpenCV path like this:
`find_package(OpenCV REQUIRED)`
After that, it worked pretty well.

**Comment by ravijo** [comment]
@bhomaidan1990 

I am glad that you made it work.

Well, I need to update the documentation with installation steps. Below are some of the importation information I can think of now:

- The package uses OpenCV-3.3.1.
  - If you don't have it, you can install it locally and point this project to use locally installed OpenCV as I did [here](https://github.com/ravijo/realsense-calibration/blob/be7070b07c1e07f2758880f674330b39374baf70/CMakeLists.txt#L5-L6).
- The original checkerboard provided by Intel RealSense is too big to print at my place. So, I am using an A3 size checkerboard, i.e., [Checkerboard-A3-40mm-9x6.pdf](https://github.com/ravijo/realsense-calibration/blob/be7070b07c1e07f2758880f674330b39374baf70/Checkerboard-A3-40mm-9x6.pdf).
  - If you are using a different checkerboard, please do not forget to [set these highlighted parameters.](https://github.com/ravijo/realsense-calibration/blob/be7070b07c1e07f2758880f674330b39374baf70/include/CalibrationManager.h#L25-L27)

I will update the documentation sometime in the future.

**Comment by bhomaidan1990** [comment]
@ravijo I tried your work with OpenCV 4.5, I had to change a few things in `CustomCalibration.cpp` to suit the new version such as:
`TermCriteria(TermCriteria::EPS | TermCriteria::MAX_ITER, 30, 0.1));` and `CALIB_FIX_ASPECT_RATIO`, `CALIB_FIX_INTRINSIC` etc ...

**Comment by ravijo** [comment]
@bhomaidan1990 

Thanks a lot.

Would you mind, sharing your code? or making a pull request labeling a new branch say OpenCV4.5?

If so, we can make this repository compatible with OpenCV 3 and 4 as well.

Thanks for your kind consideration.
